### ISSUE TITLE
ServiceMonitor exits while executing appcmd configuration

### ISSUE THREAD

**Issue by Murodese** [Microsoft/IIS.ServiceMonitor#4] opened 2017-07-30 13:56 UTC
Docker image: `microsoft/aspnet:4.6.2`

Dockerfile:
```
FROM microsoft/aspnet:4.6.2
SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]

RUN Set-ItemProperty -path 'HKLM:\SYSTEM\CurrentControlSet\Services\Dnscache\Parameters' -Name ServerPriorityTimeLimit -Value 0 -Type DWord

COPY publish/localhost/ C:/inetpub/wwwroot/site
COPY web.config C:/inetpub/wwwroot/site/web.config
COPY web.config.root C:/inetpub/wwwroot/web.config

RUN New-WebApplication -Site 'Default Web Site' -Name 'site' -PhysicalPath 'C:\inetpub\wwwroot\site'
```

Running as part of `docker-compose` brings back the following:
```
web_1        | ERROR ( message:Cannot find requested collection element. )
web_1        | ERROR ( message:Malformed collection indexer; format is [@position,name='value',name2='value2',...].  The
 @position specifier is optional, and be '@start', '@end', or '@N' where N is a numeric index into the collection. )
web_1        |
web_1        |  Service 'w3svc' has been stopped
web_1        |
web_1        | APPCMD failed with error code 4312
web_1        |
web_1        | APPCMD failed with error code 13
web_1        |
web_1        | Failed to update IIS configuration
site_web_1 exited with code 2147500037
```

The error indicates it's coming from an `appcmd set config` call, which we're not making - so presumably it's part of ServiceMonitor. For whatever reason, if the container is run manually using docker, it seems to work fine.

**Comment by shirhatti** [comment] 2017-07-31 20:56
@mcy94w ?

**Comment by shirhatti** [comment] 2017-08-03 06:26
ping @mcy94w

**Comment by andremarques023** [comment] 2017-09-25 22:45
Same issue here. Any update on this?

**Comment by bariscaglar** [comment] 2018-03-05 19:05
This is probably a dupe of an issue in IIS-Docker. @mcy94w will take a look.

**Comment by mcy94w** [comment] 2018-03-12 17:21
The same issue is being discussed in this thread https://github.com/Microsoft/iis-docker/issues/47

**Closed** 2018-03-19 17:29 UTC
Labels: duplicate
