### ISSUE TITLE
ServiceMonitor causes microsoft/iis docker container to exit with error

### ISSUE THREAD

**Issue by robertoandrade** [Microsoft/IIS.ServiceMonitor#34] opened 2018-04-30 18:21 UTC
Containers die with the following log:

```
Service 'w3svc' has been stopped
APPCMD failed with error code 259
Failed to update IIS configuration
```

Not sure if this is related at all with #29 and #4 but have been seeing this when running the `latest` tag of `microsoft:iis` on a Windows Server 2016 AMI on AWS EC2.

**Comment by mcy94w** [comment] 2018-04-30 20:50
Hi @robertoandrade :
Could you please share you Image so I can take a look?

**Comment by robertoandrade** [comment] 2018-04-30 20:51
I'm running `microsoft/iis:latest` no mods.

**Comment by mcy94w** [comment] 2018-04-30 20:55
Did you hit this issue recently?

**Comment by robertoandrade** [comment] 2018-04-30 20:57
Yes, only starting to mess with containers on Windows, after a few years of Unix. Saw this first yesterday but since I saw similar issues reported against the IIS docker repo and people seemed to always point to it being a ServiceMonitor issue that had been fixed and incorporated into the latest images I thought this could be another one of those, but different since the error code is not the same.

**Comment by michha** [comment] 2018-05-07 14:42
Maybe your _latest_ image is an old one. As of today _microsoft/iis:latest_ has an image id of _b8f924611ebb_ (created 3 weeks ago). Try a `docker pull microsoft/iis` to ensure having the latest version.
I had no problems starting a container from this image.

**Comment by vjgn** [comment] 2018-05-10 23:26
@robertoandrade, I am trying something similar to what you are doing. How did you configure your task in EC2. Look like EC2 has additional dependencies before launching the container. Exposing port 80 definitely conflicts with microsoft/iis image. From AWS docs (https://docs.aws.amazon.com/AmazonECS/latest/developerguide/windows_task_IAM_roles.html#windows_task_IAM_roles_bootstrap):

> The IAM roles for the task credential provider use port 80 on the container instance, so if you enable IAM roles for tasks on your container instance, your containers cannot use port 80 for the host port in any port mappings

There are additional bootstrap steps that must wired to the container for it launch correctly in AWS ECS. Did you get further in your testing?

**Comment by robertoandrade** [comment] 2018-05-10 23:29
Didn't do anything special, was of course exposing port 80 as a different one at the EC2 instance level to avoid that conflict, but interestingly enough, same task definition running on an ECS cluster with a different instance type works just fine, I only see problems when running the cluster with `t2.medium/large` instance types.

**Comment by me-viper** [comment] 2018-05-11 09:55
I have the same issue. 
"APPCMD failed with error code 259."
For me problem is reproduced only when containers are handled by AWS ECS. When I start same container on the same EC2 instance manually (aka docker run ...) everything works just fine.

**Comment by robertoandrade** [comment] 2018-05-11 15:37
I noticed the same @me-viper but then when I switch the instance types of my ECS cluster to something higher than a t2 it ECS launches the container just fine without errors.

**Comment by Lugoues** [comment] 2018-05-17 21:47
I see the same thing as @me-viper, and it is inconsistent. The container will fail to launch repeatedly for a time (sometime hours), and then start working.

I'm already running m5.large and m5.xlarge instances, so it may not be related?

I grabbed all the event logs from a dead container and nothing seemed out of the ordinary, I can provide them if that would help.

**Comment by mebyz** [comment] 2018-05-28 21:52
i'm experiencing the same issue on our aws ECS infrastructure

here are the steps we followed :

1. create an aws ecs windows cluster (m5.large)
2. create a task definition linked to our asp .Net app (a docker image stored on dockerhub) 

when the task starts, here is what we see in the log (cloudwatch) :

"
Service 'w3svc' has been stopped 
APPCMD failed with error code 259
Failed to update IIS configuration
"

then, the tasks stops (obviously)

just to be sure the issue is not related to our app specifically, we also tried switching our task definition to this public dockerhub image : microsoft/aspnet

but the issue is the same, and the logs are showing the same error(s)

**Comment by me-viper** [comment] 2018-05-30 07:18
At this point I have a strong feeling that it's not ServiceMonitor failing but there is weird interaction with Amazon ECS. Still trying different scenarios, but:
- Created new ECS cluster with windows machine, tasks, services etc.
- As expected container has failed to start with "APPCMD failed …"
- docker start [containerID], surely, fails too with the same error
- Then, I've just stopped Amazon ECS service and run docker start again
- Container started successfully
That kida makes sense, because it explains why starting containers manually works fine - ECS service does not care about them.
Still have to confirm that it wasn't random luck but at least it's something.

**Comment by mebyz** [comment] 2018-06-02 16:11
you're perfectly right @me-viper !

🐰 First I want to confirm that the docker image containing my app is valid : when i docker run it manually, there is no problem, even when i try directly on the ECS host instance my app runs just fine.

that fact, plus your last comment ("weird interaction with Amazon ECS") lead me to consider that the problem only occurs when my app container is started BY the ECS agent

So I wondered how ECS agent could impact the execution of the container context, and i remembered that the agent actually uses the values I entered myself in the Task Definition panel to run my container such as : network mode, memory and cpu limits, etc etc

I eventually managed to reach a stable state by tweaking my task definition (memory, cpu limits) and now my ECS service runs just fine ! 👍👍 

here you can see the values i used, which made the service become stable again : 

<img width="1511" alt="amazon_ecs" src="https://user-images.githubusercontent.com/517663/40877764-62e337f6-6686-11e8-9558-0fba28143172.png">

**Comment by mebyz** [comment] 2018-06-02 17:14
Now, i'm pretty confident in the fact the problem comes from a "memory, or ressource issue", maybe resulting in iss startup failure in the container, and the subsequent container death.

1. I reached a steady state after tweaking my ecs task definition (ie my task's memory limits)

2. That could explain the inconsistency @Lugoues experienced, as the ecs instance ressources can vary over time ( related to the instance usage )

3. That could also explain why @robertoandrade told us his app runs fine on t5 instances while experiencing fails on  t2. instances : they have less memory, cpu, ..

If you guys confirm me tweaking your task definition solves the issue for you ( as show n in my last comment ) i'll open a ticket on aws support page

Maybe they can add something to their docs about it, or fix their task creation workflow

**Comment by me-viper** [comment] 2018-06-06 08:03
One more bit that makes picture complete. Task definition UI is pretty misleading, to say the least.
We've got two things that affect CPU:

1. Task definition itself:
 <img width="818" alt="taskcpu" src="https://user-images.githubusercontent.com/487549/41023086-13765b4e-6974-11e8-909e-ecc6eb0a7947.PNG">

2. Container definition:
<img width="491" alt="containercpu" src="https://user-images.githubusercontent.com/487549/41023129-2c42dddc-6974-11e8-8ed2-9a245ff629a4.PNG">

From what I observe, if you set Task CPU > 0 (screen 1) you have to set CPU units to something > 0 (screen 2) otherwise you'll end up with CPUPercent=1. If you don't set Task CPU you need to set ECS_ENABLE_CPU_UNBOUNDED_WINDOWS_WORKAROUND=true or you, again, end up with CPUPercent=1.

I guess, that makes some sense but, for me personally, it was far from obvious.

**Comment by mebyz** [comment] 2018-06-06 08:34
Brilliant @me-viper !

**Comment by bariscaglar** [comment] 2018-06-18 23:50
@mcy94w please take a look at the error message produced by appcmd and see if service monitor can translate it to something more meaningful.

**Comment by bariscaglar** [comment] 2018-06-25 21:27
From a code point of view, we were not able to find the lower limit one needs to run the IIS container. @shirhatti will experiment to find an empirical limit.

**Comment by jeff-zohrab** [comment] 2018-08-14 17:15
@mebyz - thanks for [your post above](https://github.com/Microsoft/IIS.ServiceMonitor/issues/34#issuecomment-394098221) .  The "task definition" page specifically says "Task size is not supported for Windows containers.", so I wonder if it was just the container settings that fixed it for you.

**Comment by rymancl** [comment] 2018-09-12 17:55
@me-viper  -  For some reason the environment variable ECS_ENABLE_CPU_UNBOUNDED_WINDOWS_WORKAROUND=true isn't working for me. I set the environment variable, restarted the agent service, and even deployed new tasks. 

I have ECS Agent version 1.18.0 on the latest ECS Optimized AMI for Windows.

I do not set Task CPU or Task Memory. If I set Container CPU and Container Memory, all is fine, tasks are perfect. If I set Container CPU to 0 or do not set it, my tasks continually go to STOPPED with the error mentioned in this issue. 

I have inspected the STOPPED containers and confirmed CpuPercent is still being set to 1, not 0. If I set my Container CPU, CpuPercent get set correctly (ex: 12). 

Any idea what may be wrong here?

**Comment by me-viper** [comment] 2018-09-13 10:45
> @me-viper - For some reason the environment variable ECS_ENABLE_CPU_UNBOUNDED_WINDOWS_WORKAROUND=true isn't working for me. I set the environment variable, restarted the agent service, and even deployed new tasks.
> 
> I have ECS Agent version 1.18.0 on the latest ECS Optimized AMI for Windows. Instance is m4.xlarge.
> 
> I do not set Task CPU or Task Memory. If I set Container CPU and Container Memory, all is fine, tasks are perfect. If I set Container CPU to 0 or do not set it, my tasks continually go to STOPPED with the error mentioned in this issue.
> 
> I have inspected the STOPPED containers and confirmed CpuPercent is still being set to 1, not 0. If I set my Container CPU, CpuPercent get set correctly (ex: 12).
> 
> Any idea what may be wrong here?

I've gone through ECS Agent Code and it seems ECS_ENABLE_CPU_UNBOUNDED_WINDOWS_WORKAROUND affects only Task CPU, you still have to set Container CPU to some meaningful value. Basically, if you use this flag your task will be allowed to use all resources specified by Container CPU.

Personally, I'd avoid using this flag. Just set both Task CPU and Container CPU and call it a day.

**Comment by me-viper** [comment] 2018-09-14 11:08
Hmm. Disregard my previous answer. That is not quite what is happening. Sorry about that. 

TaskCPU indeed does nothing for windows containers. The only thing that matters for windows containers is ContainerCPU Units and ECS_ENABLE_CPU_UNBOUNDED_WINDOWS_WORKAROUND pair.

According to the code:
1. if Container CPU Units = 0 (or not set) and UNBOUNDED = true => actual container CpuPercent = 0
2. if Container CPU Units = 0 (or not set) and UNBOUNDED = false => actual container CpuPercent = 1
3. if Container CPU Units <= Physical CPUs Number * 1024 / 100 => actual container CpuPercent = 1 (UNBOUNDED is ignored)
4. otherwise, actual container CpuPercent = Container CPU Units * 100 / Physical CPUs Number * 1024 (UNBOUNDED is ignored)

For whatever reason option 1 is not working for you.

I've run several experiments and everything looks fine.
1. Created new cluster (t2.small instance)
2. Created new task definition (microsoft/iis image) with both TaskCPU and ContainerCPU empty
3. Created service with this task definition.
4. As expected continers were failing because of CpuPercent=1 (case 2)
5. Added system environment variable ECS_ENABLE_CPU_UNBOUNDED_WINDOWS_WORKAROUND=true
6. Restarted "Amazon ECS" windows service.
7. Containers started fine, CpuPercent=0 (case 1)

Hope that helps

**Comment by rymancl** [comment] 2018-09-14 12:52
@me-viper Thanks for the clarification. I was confused about _which_ CPU units the UNBOUNDED env variable was actually affecting since the ECS console does say Task CPU isn't supported by Windows containers. 

I've determined that my issue is that for whatever reason, none of my environment variables are being set via user data:
```
<powershell>
Import-Module ECSTools
[Environment]::SetEnvironmentVariable("ECS_CONTAINER_START_TIMEOUT", "30m", [System.EnvironmentVariableTarget]::Machine)
[Environment]::SetEnvironmentVariable("ECS_DISABLE_METRICS", "false", [System.EnvironmentVariableTarget]::Machine)
[Environment]::SetEnvironmentVariable("ECS_RESERVED_MEMORY", "4096", [System.EnvironmentVariableTarget]::Machine)
[Environment]::SetEnvironmentVariable("ECS_ENABLE_CPU_UNBOUNDED_WINDOWS_WORKAROUND", "true", [System.EnvironmentVariableTarget]::Machine)
Initialize-ECSAgent -Cluster 'Test-Cluster' -EnableTaskIAMRole
</powershell>
```

![image](https://user-images.githubusercontent.com/3211227/45550759-d7cbd680-b7f9-11e8-9f8c-aea4250e1937.png)

When I was testing prior, I tried setting them on the instance directly via the UI and also with Powershell, but not specifying "Machine" level. This not working was likely because of [this](https://support.microsoft.com/en-us/help/821761/changes-that-you-make-to-environment-variables-do-not-affect-services).

BUT, when I run the exact commands from my user data above on the instance, then restart the agent service, my containers do become healthy and CpuUnits=0 as expected! Also my cluster reports 4096 registered, 4096 available with 2 tasks running.

I'm going to keep digging as to why these aren't getting set properly via user data. 

Thanks again for all your help!!

**Comment by jdebbink** [comment] 2018-09-14 17:39
@rymancl after you run those command also run them like this:
```
$env:ECS_ENABLE_CPU_UNBOUNDED_WINDOWS_WORKAROUND=true
$env:ECS_DISABLE_METRICS=false
...
```

**Comment by Lugoues** [comment] 2018-10-04 19:28
I eventually gave up on using the built in service monitor and instead used a combination of this script [Wait-Service.ps1](https://github.com/MicrosoftDocs/Virtualization-Documentation/blob/live/windows-server-container-tools/Wait-Service/Wait-Service.ps1) and the following code to handle IIS environment variables.
```
Write-Output "Setting Environment Variables for Default Web App..."
$exclusionList = @('ProgramFiles(x86)', 'CommonProgramFiles(x86)','TMP','TEMP','USERNAME','USERPROFILE','APPDATA','LOCALAPPDATA','PROGRAMDATA','PSMODULEPATH','PUBLIC','USERDOMAIN','ALLUSERSPROFILE','PATHEXT','PATH','COMPUTERNAME','COMSPEC','OS','PROCESSOR_IDENTIFIER','PROCESSOR_LEVEL','PROCESSOR_REVISION','PROGRAMFILES','PROGRAMFILES','PROGRAMW6432','SYSTEMDRIVE','WINDIR','NUMBER_OF_PROCESSORS','PROCESSOR_ARCHITECTURE','SYSTEMROOT','COMMONPROGRAMFILES','COMMONPROGRAMFILES','COMMONPROGRAMW6432','DRIVERDATA')
$envVars = $(gci env:* | where-object { $_.Name -notin $exclusionList}) | ForEach-Object { "/+`"[name='DefaultAppPool'].environmentVariables.[name='$($_.Name)',value='$($_.Value)']`"" }

& 'C:/windows/system32/inetsrv/appcmd' 'set' 'config' '-section:system.applicationHost/applicationPools' $envVars '/commit:apphost'
.\Wait-Service.ps1 -ServiceName W3SVC
```
This doesn't handle duplicates properly, I ditched fixing it since it wasn't a use case we needed to support but I hope this provides someone with a way out of this ServiceMonitor headache.

**Comment by peterngai** [comment] 2018-10-09 23:56
@Lugoues, in reference to your workaround instead of using servicemonitor, are you basically implementing something like the following (taken from Dockerfile of IIS) ?  I'd like to give this a try myself, but just seeking some clarify:

FROM microsoft/windowsservercore:1803

RUN powershell -Command `
    Add-WindowsFeature Web-Server; `

Write-Output "Setting Environment Variables for Default Web App..."
$exclusionList = @('ProgramFiles(x86)', 'CommonProgramFiles(x86)','TMP','TEMP','USERNAME','USERPROFILE','APPDATA','LOCALAPPDATA','PROGRAMDATA','PSMODULEPATH','PUBLIC','USERDOMAIN','ALLUSERSPROFILE','PATHEXT','PATH','COMPUTERNAME','COMSPEC','OS','PROCESSOR_IDENTIFIER','PROCESSOR_LEVEL','PROCESSOR_REVISION','PROGRAMFILES','PROGRAMFILES','PROGRAMW6432','SYSTEMDRIVE','WINDIR','NUMBER_OF_PROCESSORS','PROCESSOR_ARCHITECTURE','SYSTEMROOT','COMMONPROGRAMFILES','COMMONPROGRAMFILES','COMMONPROGRAMW6432','DRIVERDATA')
$envVars = $(gci env:* | where-object { $_.Name -notin $exclusionList}) | ForEach-Object { "/+`"[name='DefaultAppPool'].environmentVariables.[name='$($_.Name)',value='$($_.Value)']`"" }

& 'C:/windows/system32/inetsrv/appcmd' 'set' 'config' '-section:system.applicationHost/applicationPools' $envVars '/commit:apphost'
.\Wait-Service.ps1 -ServiceName W3SVC

EXPOSE 80

**Comment by ishu3101** [comment] 2018-10-16 22:21
I'm getting the following error.

```
$ docker pull microsoft/iis
Using default tag: latest
latest: Pulling from microsoft/iis
Digest: sha256:7164927df4caa4064f291263b692d3bb842f5ca8ab9515757b5e1da6b5656112
Status: Image is up to date for microsoft/iis:latest

$ docker run -it microsoft/iis

 Service 'w3svc' has been stopped

 Service 'w3svc' started

CTRL signal received. The process will now terminate.
```

It gets stuck there until you press Ctrl+C at which point you see the **CTRL signal received. The process will now terminate** message

**Comment by shirhatti** [comment] 2018-10-16 22:31
@ishu3101 That's expected behavior. If you don't want to ServiceMonitor to block, I'd recommend running `docker run -d microsoft/iis`

**Comment by ishu3101** [comment] 2018-10-16 22:34
How do u run in interactive mode though?

**Comment by shirhatti** [comment] 2018-10-16 22:38
@ishu3101 Please file a new issue as this thread is tracking a separate issue

**Comment by ishu3101** [comment] 2018-10-17 00:04
@shirhatti Managed to figure it.

**Comment by bariscaglar** [comment] 2018-10-22 22:36
It looks like there were multiple issues being discussed but the most prominent one due to the bug in Amazon ECS is resolved with workarounds suggested. If there are other unresolved issues please file them separately.

**Closed by bariscaglar** 2018-10-22 22:36 UTC
Labels: bug

**Comment by JoseFMP** [comment] 2018-11-28 05:17
For me this issue keeps happening. No AWS here. Just bare metal.

**Comment by slavah** [comment] 2019-09-01 18:10
Issues closed ...  but same issue asp.net:4.8 docker on ECS.
Any solution except hacky workarounds?

**Comment by MattJeanes** [comment] 2021-01-05 18:01
I had exactly the same exception, but for me it was caused by CPU starvation by setting the request/limits too low in Kubernetes.

**Comment by chrisjohnson00** [comment] 2021-02-01 03:32
> I had exactly the same exception, but for me it was caused by CPU starvation by setting the request/limits too low in Kubernetes.

Sorry to bump a closed issue...
But @MattJeanes  - what requests/limits did you settle on?
Even without limits defined I get this error.

**Comment by MattJeanes** [comment] 2021-02-01 04:02
@chrisjohnson00 for me using an ASP.NET MVC app I settled on about 200 millicores and 400 megabytes of memory, if you don't have limits and your node has plenty of capacity maybe your issue is something else, but try and give it at least those in the requests and see what happens, good luck!

**Comment by caractacus** [comment] 2021-03-14 23:14
[SOLVED]
After getting stuck with this, I decided to clone the repo and make some adjustments in order to determine what causes this.

In IISConfigUtil.cpp line 231 there is a 5-second timeout for APPCMD to complete. Containers that run only IIS may achieve this, but in the real world this time limit is somewhat optimistic

I increased the timeout to 30 seconds - which seems to be necessary when more than 2 processors are available to the container. Counter-intuitive, maybe, but the load on my container on startup is very high as a legacy app was ported, and runs multiple Tomcat8 servers. .

https://github.com/microsoft/IIS.ServiceMonitor

IISConfigUtil.cpp 231: WaitForSingleObject(pi.hProcess, 30000);
Yes, docker compose would be the way to design this, but the original legacy product requires all components on a single host.

**Comment by siobam** [comment] 2021-05-03 09:42
Try to change NT service startup command type from auto to manual.

**Comment by Saibamen** [comment] 2021-05-03 12:08
> Try to change NT service startup command type from auto to manual.

This should be done in official dotnet Docker images...

**Comment by houssem11957** [comment] 2022-05-19 10:30
I faced this probelm , when i tried to run the website hosted on IIS ,
 it was my bad just using 
 `Docker run ImageName`
but intead i had to use 
`docker run --name containerName -d -p 5006:80 imagename`
i had to map the website to a specefic port 
thanks
